---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - roshaniapp.roshani
  resources:
  - roshaninotebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - roshaniapp.roshani
  resources:
  - roshaninotebooks/finalizers
  verbs:
  - update
- apiGroups:
  - roshaniapp.roshani
  resources:
  - roshaninotebooks/status
  verbs:
  - get
  - patch
  - update
