# permissions for end users to edit roshaninotebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roshaninotebook-editor-role
rules:
- apiGroups:
  - roshaniapp.roshani
  resources:
  - roshaninotebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - roshaniapp.roshani
  resources:
  - roshaninotebooks/status
  verbs:
  - get
